config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  # Incase new users need to be created
  #get  '/signup',         to: 'users#new'
  #post '/signup',         to: 'users#create'
  resources :users
  resources :posts
  resources :categories
  resources :products
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  # Index action to render all posts
  def index
    @posts = Post.all.order(created_at: :desc).paginate(page: params[:page], :per_page => 10)
  end

  # New action for creating post
  def new
    if logged_in? && current_user.admin? 
      @post = Post.new
      @categories = Category.all.map{|c| [ c.name, c.id ] }
    else
      redirect_to login_path
    end
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    @post.category_id = params[:category_id]
    if @post.save(post_params)
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
    if logged_in? && current_user.admin? 
      @post = Post.find(params[:id])
      @categories = Category.all.map{|c| [ c.name, c.id ] }
    else
      redirect_to login_path
    end
  end

  # Update action updates the post with the new information
  def update
    @post = Post.find(params[:id])
    @post.category_id = params[:category_id]
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    @post = Post.find(params[:id])
  end
  
  # The destroy action removes the post permanently from the database
  def destroy
    if logged_in? && current_user.admin? 
      @post = Post.find(params[:id])
      if @post.destroy
        flash[:notice] = "Successfully deleted post!"
        redirect_to posts_path
      else
        flash[:alert] = "Error updating post!"
      end
    else
      redirect_to login_path
    end
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :body, :description, :category_id)
  end
   
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container-center">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
    <%= simple_form_for @post do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
    
        <div class="form-group">
            <%= f.input :title, class: "form-control" %>
        </div>
    
        <div class="form-group">
            <%= f.input :description, class: "form-control" %>
        </div>
    
        <div class="form-group">
            <% if @post.category_id? %>
                <%= select_tag(:category_id, options_for_select(@categories, :selected => @post.category_id)) %>
            <% else %>
                <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select one!") %>
            <% end %>
        </div>

        <div class="form-group">
            <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
        </div>
    
        <div class="btn">
            <%= f.button :submit %>
        </div>
    <% end %>
    </div>
<div class="col-sm-2"></div>
</div>

app/views/posts/edit.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<h2>Edit Post</h2>

<%= render "posts/form" %>
</meta>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/index.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <div class="center">
  <% if @posts.any? %>
    <%= will_paginate %>
      <% @posts.each do |post| %>
        <h6>
          <%= post.created_at.strftime('%b %d, %Y') %></h6>
        </h6>
        <h3>
          <u><%= link_to "#{post.title}", post_path(post) %></u>
        </h3>
        <div class="center">
          <p>
            <%= truncate post.description, length: 300 %>
          </p>
        </div>
        <br>
      <% end %>
    <%= will_paginate %>
  </div>
  <% else %>
    <h1>Coming soon!</h1>
  <% end %>
</meta>

app/views/posts/index.html.erb
<div class="center">
  <% if @posts.any? %>
    <%= will_paginate %>
      <% @posts.each do |post| %>
        <h6>
          <%= post.created_at.strftime('%b %d, %Y') %>
        </h6>
        <h3>
          <u><%= link_to "#{post.title}", post_path(post) %></u>
        </h3>
        <div class="center">
          <p>
            <%= truncate post.description, length: 300 %>
          </p>
        </div>
        <br>
      <% end %>
    <%= will_paginate %>
  <% else %>
    <h1>Coming soon!</h1>
  <% end %>
</div>

app/views/posts/new.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<h2>Create New Post</h2>
<% if logged_in? && current_user.admin? %> 
<%= render "posts/form" %>
<% else %>
<div class="center">
<h2><%= link_to "Log in to post", login_path %></h2>
</div>
<% end %>
</meta>

app/views/posts/new.html.erb
<h2>Create New Post</h2>
<% if logged_in? && current_user.admin? %> 
<%= render "posts/form" %>
<% else %>
<div class="center">
<h2><%= link_to "Log in to post", login_path %></h2>
</div>
<% end %>

app/views/posts/show.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<div class="center">
  <h1><%= @post.title %></h1>
  <h5><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <p><%= raw @post.body %></p>
  <p><%= link_to "Return to Blog", posts_path %></p>
  <% if logged_in? %>
    <p><%= link_to "Edit", edit_post_path(@post) %></p>
    <p><%= link_to 'Delete Post', @post, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" %></p>
  <% end %>
</div>
</meta>

app/views/posts/show.html.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <div class="container-center">
    <div class="center">
      
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <h1><%= @post.title %></h1>
        <h5><%= @post.created_at.strftime('%b %d, %Y') %></h5>
        <p><%= raw @post.body %></p>
        <p><%= link_to "Return to Blog", posts_path %></p>
        <% if logged_in? %>
          <p><%= link_to "Edit", edit_post_path(@post) %></p>
          <p><%= link_to 'Delete Post', @post, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" %></p>
        <% end %>
        </div>
    <div class="col-sm-2"></div>
  </div>
</div>
</div>
</meta>