config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  # Incase new users need to be created
  #get  '/signup',         to: 'users#new'
  #post '/signup',         to: 'users#create'
  resources :users
  resources :posts
  resources :categories
  resources :products
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order(created_at: :desc).paginate(page: params[:page], :per_page => 10)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    if logged_in? && current_user.admin? 
      @category = Category.new
    else
      redirect_to login_path
    end
  end

  # GET /categories/1/edit
  def edit
    if logged_in? && current_user.admin? 
    else
      redirect_to login_path
    end
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save(category_params)
      flash[:notice] = "Successfully created category!"
      redirect_to categories_path
    else
      flash[:alert] = "Error creating new category!"
      render :new
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if logged_in? && current_user.admin? 
      if deletable?
        cat_change
        @category.destroy
        respond_to do |format|
          format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
          format.json { head :no_content }
        end
      else
        redirect_to categories_url, notice: 'Uncategorized Category can not be deleted'
      end
    else
      redirect_to login_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
    
    def cat_change
        @posts = Post.all
        @posts.each do |post|
        if post.category_id = @category.id
            post.update_attribute(:category_id, 1)
        end
      end
    end
    
    # Make Uncategorized undeletable
    def deletable?
      @category.id != 1
    end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container-center">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <%= simple_form_for(@category) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :name %>
      </div>

      <div class="btn">
        <%= f.button :submit %>
      </div>
    <% end %>
  <div class="col-sm-2"></div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<%= will_paginate %>

<h1>
  <u>Categories</u>
</h1>
<br />
    <div class="center">
      <% @categories.each do |category| %>
        <h3>
          <%= link_to "#{category.name}", category_path(category) %>
        </h3>
        <h6><%= pluralize(category.posts.count, 'post') %></h6>
        <br />
    <% end %>
<br />
<%= will_paginate %>

app/views/categories/new.html.erb
<%= render 'layouts/cat_sidebar'  %>

<h1>New Category</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="center">
<h3>
  <u><%= @category.name %></u>
</h3>
<% if logged_in? && current_user.admin? %>
  <p><blog-headers><%= link_to "New Post", new_post_path %></blog-headers></p>
  <p><blog-headers><%= link_to 'Edit', edit_category_path(@category) %> | 
  <%= link_to 'Delete', @category, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<% end %>
<%= link_to 'Back', categories_path %></blog-headers></p>
<br />
<br />
<% if @category.posts.any? %>
  <% @category.posts.each do |post| %>
      <h6>
        <%= post.created_at.strftime('%b %d, %Y') %></h6>
      </h6>
      <h3>
        <u><%= link_to "#{post.title}", post_path(post) %></u>
      </h3>
      <div class="center">
        <p>
          <%= truncate post.description, length: 300 %>
        </p>
      </div>
      <br />
  <% end %>
<% else %>
  <p>There are no posts in this category</p>
<% end %>
</div>