config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  # Incase new users need to be created
  #get  '/signup',         to: 'users#new'
  #post '/signup',         to: 'users#create'
  resources :users
  resources :posts
  resources :categories
  resources :products
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :picture, PictureUploader
    validates :title,  presence: true, length: { maximum: 300 }
    PRICE_REGEXP = /\A\d{1,4}(\.\d{0,2})?\z/
    validates :price, presence: true,
                      numericality: true,
                      format: { with: PRICE_REGEXP }
    validates :description, presence: true, length: { maximum: 1000 }, 
                            allow_nil: true
    validate :picture_size
    
    private
    
        def picture_size
            if picture.size > 5.megabytes
                errors.add(:picture, "must be less than 5MB")
            end
        end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order(created_at: :desc).paginate(page: params[:page], :per_page => 10)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    if logged_in? && current_user.admin? 
      @product = Product.new
    else
      redirect_to login_path
    end
  end

  # GET /products/1/edit
  def edit
    if logged_in? && current_user.admin?
    else
      redirect_to login_path
    end
  end

  # POST /products
  # POST /products.json
  #def create
    #@product = Product.new(product_params)

    #respond_to do |format|
      #if @product.save
        #format.html { redirect_to @product, notice: 'Product was successfully created.' }
        #format.json { render :show, status: :created, location: @product }
      #else
        #format.html { render :new }
        #format.json { render json: @product.errors, status: :unprocessable_entity }
      #end
    #end
  #end
  
  def create
    @product = Product.new(product_params)
    if @product.save
      flash.now[:success] = "Listing Created"
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end
  
  def update 
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash.now[:success] = "Listing Updated"
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end
  
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  #def update
    #respond_to do |format|
      #if @product.update(product_params)
        #format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        #format.json { render :show, status: :ok, location: @product }
      #else
        #format.html { render :edit }
        #format.json { render json: @product.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    if logged_in? && current_user.admin? 
      @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to login_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :description, :picture, :paypalbutton, :active)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container-center">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
    <%= simple_form_for @product do |p| %>
    <%= render 'shared/error_messages', object: p.object %>
    
        <div class="form-group">
            <%= p.input :title, class: "form-control" %>
        </div>
    
        <div class="form-group">
            <%= p.input :description, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= p.input :price, class: "form-control" %>
        </div>
        
        <div class="form-group">
            <%= p.input :paypalbutton, class: "form-control" %>
        </div>
        
        <div class="form-group">
            <%= p.input :active, class: "form-control" %>
        </div>
        
        <span class="picture">
            <%= p.file_field :picture %>
        </span>
        
        <div class="btn">
            <%= p.button :submit %>
        </div>
        
    <% end %>
    </div>
<div class="col-sm-2"></div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<div class="center">
<% if @products.any? %>  

  <%= will_paginate %>
  <% @products.each do |product| %>
      <h3>
        <u><%= link_to "#{product.title}", product_path(product) %></u>
      </h3>
      <div class="center">
        <%= image_tag product.picture.url if product.picture? %>
          <% if product.active == false %>
            <p>Sorry, this product is not available at this time.</p>
          <% else %>
             <div id="paypalbutton"><%= raw product.paypalbutton %></div>
          <% end %>
          <br />
      </div>
      <br>
  <% end %>
  <%= will_paginate %>
  
<% else %>
  <h1>Coming soon!</h1>
<% end %>
</div>
</meta>

app/views/products/index.html.erb
<div class="container-center">
<% if @products.any? %>  
  
<% @products.in_groups_of(4, false) do |group| %>
  <% for product in group %>
    <ul class="nav navbar-nav">
      <li>
        <div class="card" style="width: 25rem;">
          
          <% if product.picture? %>
            <%= link_to(image_tag(product.picture.url), product_path(product) ) %>
          <% end %>
          
  
          <div class="card-block">
            <h3 class="card-title">
              <u><%= link_to "#{product.title}", product_path(product) %></u>
            </h3>
            
            <div class="center">
              $<%= product.price %>
              <% if product.active == false %>
                <p class="card-text">Sorry, this product is not available at this time.</p>
              <% else %>
                <div class="card-text" id="paypalbutton"><%= raw product.paypalbutton %></div>
              <% end %>
            </div>
            
          </div>
        </div>
      </li>
    </ul>
  <% end %>
<% end %>

<% else %>
  <h1>Coming soon!</h1>
<% end %>
</div>

app/views/products/new.html.erb
<h2>Create New Product</h2>
<% if logged_in? && current_user.admin? %> 
<%= render "products/form" %>
<% else %>
<div class="center">
<h2><%= link_to "Log in to post", login_path %></h2>
</div>
<% end %>

app/views/products/show.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <div class="container-center">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <h1><%= @product.title %></h1>
         <%= image_tag @product.picture.url if @product.picture? %>
        <h5><%= @product.description %></h5>
          <% if @product.active == false %>
            <p>Sorry, this product is not available at this time.</p>
          <% else %>
             <div id="paypalbutton"><%= raw @product.paypalbutton %></div>
          <% end %>
          <br />
        <p><%= link_to "Return to Store", products_path %></p>
        <% if logged_in? %>
          <p><%= link_to "Edit", edit_product_path(@product) %></p>
          <p><%= link_to 'Delete', @product, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" %></p>
        <% end %>
        </div>
    <div class="col-sm-2"></div>
  </div>
</div>
</meta>

app/views/products/show.html.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <div class="container-center">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <h1><%= @product.title %></h1>
         <%= image_tag @product.picture.url if @product.picture? %>
        <h5><%= @product.description %></h5>
        $<%= @product.price %>
          <% if @product.active == false %>
            <p>Sorry, this product is not available at this time.</p>
          <% else %>
            <div id="paypalbutton"><%= raw @product.paypalbutton %></div>
          <% end %>
          <br />
        <p><%= link_to "Return to Store", products_path %></p>
        <% if logged_in? %>
          <p><%= link_to "Edit", edit_product_path(@product) %></p>
          <p><%= link_to 'Delete', @product, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" %></p>
        <% end %>
        </div>
    <div class="col-sm-2"></div>
  </div>
</div>
</meta>