config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  # Incase new users need to be created
  #get  '/signup',         to: 'users#new'
  #post '/signup',         to: 'users#create'
  resources :users
  resources :posts
  resources :categories
  resources :products
end

app/views/layouts/_application_layout.html.erb
<body>
    <div class="container">
      <% if flash.any? %>
        <% flash.keys.each do |flash_key| %>
          <% next if flash_key.to_s == 'timedout' %>
            <div class="alert-message <%= flash_key %>">
            <a class="close" data-dismiss="alert" href="#"> x</a>
            <% flash.discard(flash_key) %>
            </div>
        <% end %>
      <% end %>

      <%= yield %>
      <% #debug(params) if Rails.env.development? %>
    </div>
</body>

app/views/layouts/_cat_sidebar.html.erb
<div class="column col-xs-3" id="sidebar">
        <div class="sidebar-nav-fixed pull-right affix">    
                <ul class="nav">
                    <div class="center">
                    <ul><h5>Categories</h5></ul>
                    <% @categories = Category.all.order(created_at: :desc) %>
                    <% @categories.each do |category| %>
                        <ul id="p-side">
                            <blog-headers>
                                <%= link_to "#{category.name}", category_path(category) %>
                                <% if logged_in? && current_user.admin? %>
                                    <%= link_to 'x', category, method: :delete, :onclick => "return confirm('Are you sure you want to delete this category?')" %>
                                <% end %>
                            </blog-headers>
                
                        </ul>
                    <% end %>
                    </div>
                </ul>
        </div>    
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
        <% if logged_in? && current_user.admin? %>
            <%= render 'layouts/logged_in_header' %>
        <% end %>
        <div class="container"><%= link_to "Emma  Cate", root_path, id: "logo" %></div>
        <div class="container"><%= link_to "Spiritual Advisor", root_path, id: "logo-two" %></div>
    </div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Services", about_path, method: :get, id: "logo-three" %></li>
                <li><%= link_to "Contact", contact_path, id: "logo-three" %></li>
                <li><%= link_to "Store", products_path, id: "logo-three" %></li>
                <li><%= link_to "Blog", posts_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_insta_button.html.erb
<style>.ig-b- { display: inline-block; }
.ig-b- img { visibility: hidden; }
.ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
.ig-b-32 { width: 32px; height: 32px; background: url(//badges.instagram.com/static/images/ig-badge-sprite-32.png) no-repeat 0 0; }
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
.ig-b-32 { background-image: url(//badges.instagram.com/static/images/ig-badge-sprite-32@2x.png); background-size: 60px 178px; } }</style>
<a href="https://www.instagram.com/metaphysically8/?ref=badge" class="ig-b- ig-b-32"><img src="//badges.instagram.com/static/images/ig-badge-32.png" alt="Instagram" /></a>

app/views/layouts/_logged_in_header.html.erb
<div class="center">
    <%= render 'layouts/menu' %>
</div>

app/views/layouts/_menu.html.erb
<div class="menu-header" onclick="openNav()">Menu</div>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <%= link_to "Home", root_path, id: "logo-three-phone" %>
      <%= link_to "Blog", posts_path, id: "logo-three-phone" %>
      <%= link_to "About", about_path, id: "logo-three-phone" %>
      <%= link_to "Store", products_path, id: "logo-three-phone" %>
      <%= link_to "New Product", new_product_path, id: "logo-three-phone" %>
      <%= link_to "New Post", new_post_path, id: "logo-three-phone" %>
      <%= link_to "New Category", new_category_path, id: "logo-three-phone" %>
      <%= link_to "Edit Profile", edit_user_path(current_user), id: "logo-three-phone" %>
      <%= link_to "Log out", logout_path, method: "delete", id: "logo-three-phone" %>
</div>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.body.style.backgroundColor = "white";
}
</script>

app/views/layouts/_menu_phone.html.erb
<div class="container-center">
<nav>
<div class="menu-header-phone" onclick="openNav()">Menu</div>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <%= link_to "Home", root_path, id: "logo-three-phone" %>
      <%= link_to "About", about_path, id: "logo-three-phone" %>
      <%= link_to "Contact", contact_path, id: "logo-three-phone" %>
      <%= link_to "Blog", posts_path, id: "logo-three-phone" %>
      <%= link_to "Store", products_path, id: "logo-three-phone" %>
      <% if logged_in? && current_user.admin? %>
        <%= link_to "Log out", logout_path, method: "delete", id: "logo-three-phone" %>
        <%= link_to "Edit Profile", edit_user_path(current_user), id: "logo-three-phone" %>
        <%= link_to "New Product", new_product_path, id: "logo-three-phone" %>
        <%= link_to "New Post", new_post_path, id: "logo-three-phone" %>
        <%= link_to "New Category", new_category_path, id: "logo-three-phone" %>
      <% end %>
</div>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.body.style.backgroundColor = "white";
}
</script>
</nav>
</div>

app/views/layouts/_phone_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="center">
    <div class="container">
        <div class="container" id="logo-phone">Emma  Cate</div>
        <div class="container" id="logo-phone-two">Spiritual Advisor</div>
    </div>
    </div>
    <br />
    <%= render 'layouts/menu_phone' %>
</header>

app/views/layouts/_phone_header_home.html.erb
<header class="navbar navbar-fixed-bottom">
    <div class="center">
    <div class="container">
        <div class="container" id="logo-phone">Emma  Cate</div>
        <div class="container" id="logo-phone-two">Spiritual Advisor</div>
    </div>
    </div>
    <br />
    <%= render 'layouts/menu_phone' %>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:url"           content="www.emmacate8.com" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Emma Cate, Spiritual Advisor" />
  <meta property="og:description"   content="Emma Cate, Spiritual Advisor" />
  <meta property="og:image"         content="assets/ForChristianPhone.jpg" />
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <% if current_page?(root_url) %>
        <%= render 'layouts/phone_header_home' %>
      <% else %>
        <%= render 'layouts/phone_header' %>
      <% end %>
  </head>
    <body>
      <%= render 'layouts/application_layout' %>
    </body>
</html>
<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Pinyon+Script" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Italianno|Mr+De+Haviland" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Miss+Fajardose|Monsieur+La+Doulaise|Rouge+Script" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:url"           content="www.emmacate8.com" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Emma Cate, Spiritual Advisor" />
  <meta property="og:description"   content="Emma Cate, Spiritual Advisor" />
  <meta property="og:image"         content="assets/ForChristianPhone.jpg" />
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= favicon_link_tag 'favicon-infinity.png' %>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/header' %>
  </head>
  <body>
    <%= render 'layouts/application_layout' %>
  </body>
</html>

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Pinyon+Script" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Italianno|Mr+De+Haviland" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Miss+Fajardose|Monsieur+La+Doulaise|Rouge+Script" rel="stylesheet">